#spring.application.name=money-prime
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/money_prime_db
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8087
  servlet:
    context-path: /money-prime